name: Frontend SonarQube Quality Check

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "Application/frontend/**"
      - ".github/workflows/frontend-sonarqube.yml"

permissions:
  contents: read

jobs:

  sonarqube:

    name: Frontend SonarQube Scan
    runs-on: ubuntu-latest

    steps:

      # ==================================================
      # 1. Checkout source code
      # ==================================================
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      # ==================================================
      # 2. Setup Java
      # SonarScanner requires Java
      # ==================================================
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"


      # ==================================================
      # 3. SonarQube Scan
      # ==================================================
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: Application/frontend
          args: >
            -Dsonar.projectKey=frontend
            -Dsonar.projectName=Frontend
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8


      # ==================================================
      # 4. Quality Gate
      # ==================================================
      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        timeout-minutes: 10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}