name: Frontend SonarQube Quality Check

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "Application/frontend/**"
      - ".github/workflows/frontend-sonarqube.yml"

permissions:
  contents: read

jobs:
  sonarqube:

    runs-on: ubuntu-latest

    steps:

      # ------------------------------------------
      # 1. Checkout
      # ------------------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ------------------------------------------
      # 2. Java
      # ------------------------------------------
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # ------------------------------------------
      # 3. SonarQube Scan
      # ------------------------------------------
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: Application/frontend
          args: >
            -Dsonar.projectKey=frontend
            -Dsonar.projectName=Frontend
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8

      # ------------------------------------------
      # 4. Check scanner report
      # ------------------------------------------
      - name: Check SonarQube scan result
        run: |
          echo "Checking SonarQube scanner files..."

          if [ -f "Application/frontend/.scannerwork/report-task.txt" ]; then
            echo "SonarQube report found."
            cat Application/frontend/.scannerwork/report-task.txt
          else
            echo "ERROR: SonarQube report not found."
            echo "Contents of Application/frontend:"
            ls -la Application/frontend
            exit 1
          fi

      # ------------------------------------------
      # 5. Quality Gate
      # ------------------------------------------
      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        timeout-minutes: 10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          scanMetadataReportFile: Application/frontend/.scannerwork/report-task.txt